### ISSUE TITLE
4 connected or 8 connected?

### ISSUE THREAD

**Issue by ldenoue** [bramp/Connected-component-labelling#2]
Do you know if this algorithm computes the 4-connected or 8-connected components?

**Comment by bramp** [comment]
Oh it's been a long time since I wrote this, but [looking at the code](https://github.com/bramp/Connected-component-labelling/blob/84fd9783b2d57d88e6bf52472e49b101c05e52cd/connected-component-labelling.js#L87) it is 8 ways.
